# Generated by Django 2.1.5 on 2022-12-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20221221_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('Seta Nf-e', 'Usuário pode alterar parametro Nf-e'), ('Permissão2', 'Permissão 2'), ('Permissão3', 'Permissão 3'))},
        ),
    ]
