# Generated by Django 2.1.5 on 2022-12-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20221228_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parametro Nf-e'), ('Permissão2', 'Permissão 2'), ('Permissão3', 'Permissão 3'))},
        ),
    ]
