# Generated by Django 2.1.5 on 2022-12-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20221228_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('Seta Nf-e', 'Usuário pode alterar parametro Nf-e'), ('ver_dashboard', 'Pode visualizar o dashboard'), ('Permissão3', 'Permissão 3'))},
        ),
    ]
