# Generated by Django 2.1.5 on 2022-12-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20221229_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Person'),
        ),
    ]
