# Generated by Django 2.1.5 on 2022-12-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20221220_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar clientes'),)},
        ),
    ]
